DROP TABLE IF EXISTS customer;

CREATE TABLE customer (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(20) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  city VARCHAR(50) DEFAULT NULL,
  address VARCHAR(100) DEFAULT NULL
);
